import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar, { SidebarItem } from "../components/Sidebar";
import { Home, LayoutDashboard, Play, Database } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar>
            <SidebarItem icon={<Home size={20} />} text="Home" href="/" />
            <SidebarItem icon={<LayoutDashboard size={20} />} text="Dashboard" href="/dashboard" />
            <SidebarItem icon={<Play size={20} />} text="Playground" href="/playground" />
            <li className="my-3"><hr className="border-gray-200" /></li>
            <SidebarItem 
              icon={<Database size={20} />} 
              text="Supabase Data" 
              href="https://app.supabase.com/" 
              target="_blank" 
            />
          </Sidebar>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
