'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar, { SidebarItem } from "../components/Sidebar";
import { Home, LayoutDashboard, Play, Database, Menu } from "lucide-react";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <Sidebar isMobileMenuOpen={isMobileMenuOpen} setMobileMenuOpen={setIsMobileMenuOpen}>
            <SidebarItem icon={<Home size={20} />} text="Home" href="/" />
            <SidebarItem icon={<LayoutDashboard size={20} />} text="Dashboard" href="/dashboard" />
            <SidebarItem icon={<Play size={20} />} text="Playground" href="/playground" />
            <li className="my-3"><hr className="border-gray-200" /></li>
            <SidebarItem 
              icon={<Database size={20} />} 
              text="Supabase Data" 
              href="https://app.supabase.com/" 
              target="_blank" 
            />
          </Sidebar>
          <div className="flex-1 flex flex-col">
            <div className="md:hidden flex items-center justify-between p-4 border-b">
              <img src="https://img.logoipsum.com/243.svg" className="w-24" alt="logo" />
              <button onClick={() => setIsMobileMenuOpen(true)}>
                <Menu size={24} />
              </button>
            </div>
            <main className="flex-1 bg-gray-50">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
